<a href="https://colab.research.google.com/github/nsit-karan/numpy-pandas/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello world. pandas and numpy in action")

hello world. pandas and numpy in action


In [5]:
import numpy as np

In [9]:
python_list = [1,2,3,4,5]
numpy_arr = np.array([1,2,3,4,5])

print(python_list)
print(numpy_arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [11]:
# not allowed python_list + 5
numpy_arr + 5

array([ 6,  7,  8,  9, 10])

In [12]:
numpy_arr*5

array([ 5, 10, 15, 20, 25])

In [13]:
numpy_arr.size

5

In [15]:
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
arr2 = np.arange(20, 38, 2)
arr2

array([20, 22, 24, 26, 28, 30, 32, 34, 36])

In [19]:
arr2.mean()

28.0

In [20]:
arr2.max()

36

In [22]:
arr2 > 25

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [23]:
# from the list, provide values greater than 25
arr2[arr2 > 25]

array([26, 28, 30, 32, 34, 36])

In [25]:
!gdown 1PQhT_-kTg1jhTKFqOU-5MzQ4gARu-V3a

Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1PQhT_-kTg1jhTKFqOU-5MzQ4gARu-V3a 



In [26]:
!gdown https://drive.google.com/uc?id=1PQhT_-kTg1jhTKFqOU-5MzQ4gARu-V3a

Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1PQhT_-kTg1jhTKFqOU-5MzQ4gARu-V3a 



In [27]:
!gdown https://drive.google.com/uc?id=1PQhT_-kTg1JhTKFq0U-5MzQ4gARu-V3a

Downloading...
From: https://drive.google.com/uc?id=1PQhT_-kTg1JhTKFq0U-5MzQ4gARu-V3a
To: /content/survey_large.txt
100% 21.8M/21.8M [00:00<00:00, 261MB/s]


In [28]:
scores = np.loadtxt('survey_large.txt')

In [30]:
scores.size

10000000

In [31]:
scores.min()

1.0

In [33]:
scores.mean()

7.250214

In [37]:
detractors = scores[scores < 7]
print(detractors)

[5. 4. 4. ... 5. 4. 5.]


In [38]:
detractors.size

2844902

In [39]:
promotors = scores[scores >= 9]
print(promotors)

[10.  9.  9. ... 10.  9.  9.]


In [40]:
promotors.size

5218510

In [42]:
nps = 100*(promotors.size - detractors.size)/scores.size
nps

23.73608